---
stages:
  - prepare
  - python
  - compile
  - fortran
  - statistics
  - finalize


###################################################################################################
default:
  before_script:
    - ${LOCAL_HOME}/bin/queue ${CI_JOB_ID} ${TOKEN}
    - source env/DAMASK.sh
    - export PATH=${TESTROOT}/bin:${PATH}
    - echo Job start:" $(date)"
  after_script:
    - echo Job end:" $(date)"


###################################################################################################
variables:
  # ===============================================================================================
  # GitLab Settings
  # ===============================================================================================
  GIT_SUBMODULE_STRATEGY: normal

  # ===============================================================================================
  # Shortcut names
  # ===============================================================================================
  TESTROOT:   "$LOCAL_HOME/GitLabCI_Pipeline_$CI_PIPELINE_ID"

  # ===============================================================================================
  # Names of module files to load
  # ===============================================================================================
  # ++++++++++++ Compiler/MPI/PETSc +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  COMPILER_INTEL: "Compiler/Intel/2022.0.1 Libraries/IMKL/2022.0.1"
  MPI_INTEL: "MPI/Intel/2022.0.1/IntelMPI/2021.5.0"
  PETSC_INTEL: "Libraries/PETSc/3.16.5/Intel-2022.0.1-IntelMPI-2021.5.0"
  # ++++++++++++ MSC Marc +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  MSC: "FEM/MSC/2024.1"
  IntelMarc: "Compiler/Intel/2022.0.1 Libraries/IMKL/2022.0.1"
  HDF5Marc: "HDF5/1.12.1/Intel-2022.0.1"


###################################################################################################

create_testroot:
  stage: prepare
  before_script:
    - ${LOCAL_HOME}/bin/queue ${CI_JOB_ID} ${TOKEN}
    - echo Job start:" $(date)"
  script:
    - mkdir -p ${TESTROOT}

.on_merge:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

###################################################################################################

.python_base:
  stage: python
  image: git.damask-multiphysics.org:5050/damask/damask/python:$PYTHON_IMAGE
  tags:
    - matesting2-container-runner
  before_script:
    - python --version
    - pip list

.python_default:
  extends: .python_base
  variables: {PYTHON_IMAGE: 2025.02.25}

.python_min:
  extends: .python_base
  variables: {PYTHON_IMAGE: '310_2412'}


.create_package:
  script:
    - sed -i 's/-[[:digit:]]*-.*//' VERSION
    - cd python
    - python3 -m build --wheel --no-isolation

create_package:
  extends:
    - .create_package
    - .python_default

create_package_min:
  extends:
    - .create_package
    - .python_min
    - .on_merge


.pytest:
  script:
    - export DAMASK_ROOT=$(pwd)
    - PYTHONPATH=${DAMASK_ROOT}/python:$PYTHONPATH
    - cd python
    - python3 -m pytest -v --cov=damask --cov-report=xml --damask-root=${DAMASK_ROOT}
    - coverage report --fail-under=90 --show-missing

pytest:
  extends:
    - .pytest
    - .python_default

pytest_min:
  extends:
    - .pytest
    - .python_min
    - .on_merge


doctest:
  extends: .python_default
  script:
    - export DAMASK_ROOT=$(pwd)
    - PYTHONPATH=${DAMASK_ROOT}/python:$PYTHONPATH
    - cd python
    - python3 -m pytest -v --doctest-modules -k 'not result and not configmaterial and not orientation and not rotation and not geomgrid' damask

mypy:
  extends: .python_default
  script:
    - cd python
    - mypy damask

###################################################################################################

.unittest:
  stage: compile
  tags:
    - matesting2-container-runner
  script:
    - source env/DAMASK.sh
    - cd ${TEMPDIR}
    - ./bin/DAMASK_test
    - find . -name '*.gcda' -not -path "**/test/*" -exec gcov {} \;

# -------------------------------------------------------------------------------------------------

unittest_GCC_DEBUG:
  extends: .unittest
  image: git.damask-multiphysics.org:5050/damask/damask/gcc_petsc-debug:2025.03.10
  before_script:
    - TEMPDIR=$(mktemp -d /tmp/tmp.XXXXXXXXXX)
    - cmake -B ${TEMPDIR} -DDAMASK_SOLVER=test -DCMAKE_INSTALL_PREFIX=${TEMPDIR} -DCMAKE_BUILD_TYPE=DEBUG -DBUILDCMD_POST=-coverage
    - cmake --build ${TEMPDIR} --target install

unittest_GCC_RELEASE:
  extends: .unittest
  image: git.damask-multiphysics.org:5050/damask/damask/gcc_petsc-default:2025.03.10
  before_script:
    - TEMPDIR=$(mktemp -d /tmp/tmp.XXXXXXXXXX)
    - cmake -B ${TEMPDIR} -DDAMASK_SOLVER=test -DCMAKE_INSTALL_PREFIX=${TEMPDIR} -DCMAKE_BUILD_TYPE=RELEASE -DBUILDCMD_POST=-coverage
    - cmake --build ${TEMPDIR} --target install

unittest_GCC_PERFORMANCE:
  extends: .unittest
  image: git.damask-multiphysics.org:5050/damask/damask/gcc_petsc-default:2025.03.10
  before_script:
    - TEMPDIR=$(mktemp -d /tmp/tmp.XXXXXXXXXX)
    - cmake -B ${TEMPDIR} -DDAMASK_SOLVER=test -DCMAKE_INSTALL_PREFIX=${TEMPDIR} -DCMAKE_BUILD_TYPE=PERFORMANCE -DBUILDCMD_POST=-coverage
    - cmake --build ${TEMPDIR} --target install

# -------------------------------------------------------------------------------------------------

unittest_oneAPI_DEBUG:
  extends: .unittest
  image: git.damask-multiphysics.org:5050/damask/damask/oneapi_petsc-debug:2025.03.09
  before_script:
    - TEMPDIR=$(mktemp -d /tmp/tmp.XXXXXXXXXX)
    - cmake -B ${TEMPDIR} -DDAMASK_SOLVER=test -DCMAKE_INSTALL_PREFIX=${TEMPDIR} -DCMAKE_BUILD_TYPE=DEBUG
    - cmake --build ${TEMPDIR} --target install

unittest_oneAPI_RELEASE:
  extends: .unittest
  image: git.damask-multiphysics.org:5050/damask/damask/oneapi_petsc-default:2025.03.09
  before_script:
    - TEMPDIR=$(mktemp -d /tmp/tmp.XXXXXXXXXX)
    - cmake -B ${TEMPDIR} -DDAMASK_SOLVER=test -DCMAKE_INSTALL_PREFIX=${TEMPDIR} -DCMAKE_BUILD_TYPE=RELEASE
    - cmake --build ${TEMPDIR} --target install

unittest_oneAPI_PERFORMANCE:
  extends: .unittest
  image: git.damask-multiphysics.org:5050/damask/damask/oneapi_petsc-default:2025.03.09
  before_script:
    - TEMPDIR=$(mktemp -d /tmp/tmp.XXXXXXXXXX)
    - cmake -B ${TEMPDIR} -DDAMASK_SOLVER=test -DCMAKE_INSTALL_PREFIX=${TEMPDIR} -DCMAKE_BUILD_TYPE=PERFORMANCE
    - cmake --build ${TEMPDIR} --target install

###################################################################################################

.compile:
  stage: compile
  tags:
    - matesting2-container-runner
  before_script:
    - tail +$(grep -n 'Configure Actions.*' /petsc/configure.log | cut -f 1 -d:) /petsc/configure.log
    - source env/DAMASK.sh
    - cd PRIVATE/testing

.compile_grid:
  extends: .compile
  script:
    - python -m pytest -k 'compile and grid'

.compile_mesh:
  extends: .compile
  script:
    - python -m pytest -k 'compile and mesh'

grid_GCC:
  extends: .compile_grid
  image: git.damask-multiphysics.org:5050/damask/damask/gcc_petsc-default:2025.03.10

mesh_GCC:
  extends: .compile_mesh
  image: git.damask-multiphysics.org:5050/damask/damask/gcc_petsc-default:2025.03.10

grid_GCC-i64:
  extends: .compile_grid
  image: git.damask-multiphysics.org:5050/damask/damask/gcc_petsc-i64:2025.03.10

mesh_GCC-i64:
  extends: .compile_mesh
  image: git.damask-multiphysics.org:5050/damask/damask/gcc_petsc-i64:2025.03.10

grid_oneAPI:
  extends: .compile_grid
  image: git.damask-multiphysics.org:5050/damask/damask/oneapi_petsc-default:2025.03.09

mesh_oneAPI:
  extends: .compile_mesh
  image: git.damask-multiphysics.org:5050/damask/damask/oneapi_petsc-default:2025.03.09


Marc_Intel:
  stage: compile
  tags:
    - bare-metal
  script:
    - module load $IntelMarc $HDF5Marc $MSC
    - cd PRIVATE/testing
    - pytest -k 'compile and Marc' --basetemp ${TESTROOT}/compile_Marc

setup_Marc:
  stage: compile
  tags:
    - bare-metal
  script:
    - module load $IntelMarc $HDF5Marc $MSC
    - cd $(mktemp -d)
    - cp ${CI_PROJECT_DIR}/examples/Marc/* .
    - python3 -c "import damask;damask.solver.Marc().submit_job('r-value','texture',True,'h')"
    - mkdir -p ${TESTROOT}/src/Marc
    - mv ${CI_PROJECT_DIR}/src/Marc/DAMASK_Marc.marc ${TESTROOT}/src/Marc


###################################################################################################
open-source_grid_GCC:
  stage: fortran
  tags:
    - matesting2-container-runner
  image: git.damask-multiphysics.org:5050/damask/damask/gcc_petsc-default:2025.03.10
  before_script:
    - cmake -DDAMASK_SOLVER=GRID && make -j2 all install
    - source env/DAMASK.sh
  script:
    - cd PRIVATE/testing
    - pytest -k 'not compile and grid and not signal and not restart'

open-source_grid_signal_restart:
  stage: fortran
  tags:
    - bare-metal
  before_script:
    - module load ${COMPILER_INTEL} ${MPI_INTEL} ${PETSC_INTEL}
    - cd $(mktemp -d)
    - cmake -DDAMASK_SOLVER=GRID -DCMAKE_INSTALL_PREFIX=${TESTROOT} ${CI_PROJECT_DIR}
    - make -j2 all install
    - export PATH=${TESTROOT}/bin:${PATH}
    - cd ${CI_PROJECT_DIR}
    - source env/DAMASK.sh
    - echo Job start:" $(date)"
  script:
    - cd PRIVATE/testing
    - pytest -k 'not compile and grid and (signal or restart)' -m 'not cifail' --basetemp ${TESTROOT}/open-source -v
  after_script:
    - echo Job end:" $(date)"

open-source_mesh_GCC:
  tags:
    - matesting2-container-runner
  image: git.damask-multiphysics.org:5050/damask/damask/gcc_petsc-default:2025.03.10
  stage: fortran
  before_script:
    - make mesh
    - source env/DAMASK.sh
  script:
    - cd PRIVATE/testing
    - pytest -k 'not compile and mesh'

Marc:
  stage: fortran
  tags:
    - bare-metal
  script:
    - cd PRIVATE/testing
    - pytest -k 'not compile and Marc' -m 'not cifail' --damask-root=${TESTROOT} --basetemp ${TESTROOT}/Marc -v

# Needs closer look
# Phenopowerlaw_singleSlip:
#   stage: fortran
#   script: Phenopowerlaw_singleSlip/test.py


###################################################################################################
grid_performance:
  stage: statistics
  tags:
    - bare-metal
  before_script:
    - ${LOCAL_HOME}/bin/queue ${CI_JOB_ID} ${TOKEN} --blocking
    - source env/DAMASK.sh
    - echo Job start:" $(date)"
  script:
    - module load ${COMPILER_INTEL} ${MPI_INTEL} ${PETSC_INTEL}
    - cd $(mktemp -d)
    - cmake -DOPTIMIZATION=AGGRESSIVE -DDAMASK_SOLVER=GRID -DCMAKE_INSTALL_PREFIX=./ ${CI_PROJECT_DIR}
    - make -j2 all install
    - export PATH=${PWD}/bin:${PATH}
    - cd $(mktemp -d)
    - git clone -q git@git.damask-multiphysics.org:damask/statistics.git .
    - ./measure_performance.py --input_dir ${CI_PROJECT_DIR}/examples/grid --tag ${CI_COMMIT_SHA}
    - >
        if [ ${CI_COMMIT_BRANCH} == development ]; then
          git add performance.txt
          git commit -m ${CI_PIPELINE_ID}_${CI_COMMIT_SHA}
          git push
        fi


###################################################################################################
update_website_master:
  stage: finalize
  trigger:
    project: damask/website
    branch: master
  only:
    - development

update_website_3.0:
  stage: finalize
  trigger:
    project: damask/website
    branch: "3.0"
  only:
    - "3.0"

update_revision:
  stage: finalize
  tags:
    - bare-metal
  before_script:
    - ${LOCAL_HOME}/bin/queue ${CI_JOB_ID} ${TOKEN}
    - echo Job start:" $(date)"
  script:
    - cd $(mktemp -d)
    - git clone -q git@git.damask-multiphysics.org:damask/DAMASK.git .
    - git pull
    - export VERSION=$(git describe ${CI_COMMIT_SHA})
    - echo ${VERSION:1} > VERSION
    - >
       git diff-index --quiet HEAD ||
       git commit VERSION -m "[skip ci] updated version information after successful test of $VERSION"
    - if [ ${CI_COMMIT_SHA} == $(git rev-parse HEAD^) ]; then git push --atomic --no-verify origin HEAD:development HEAD:master; fi
  only:
    - development
