type: quadEnergy

components:
  H:
    M: 1
    c_eq: 1
    G,c: 1
    G,c^2: 1
    dependent: False
  Cl:
    M: 1
    c_eq: 1
    G,c: 1
    G,c^2: 1
    dependent: False # default
  Cu:
    M: 1
    c_eq: 1
    G,c: 1
    G,c^2: 1
    dependent: True
